### ISSUE TITLE
Make `HeightMap` and `Chunk` iterators work with `const`

### ISSUE THREAD

**Issue by dxrcy** [rozukke/mcpp#104]
`for (const int height : heights);` does not work if `heights` is `const`.

I believe function overloading can be used to create both a `const` and non-`const` iterator for `HeightMap` and `Chunk`.

I will attempt a PR when I get time.

**Comment by dxrcy** [comment]
Will be closed if #106 is merged.

**Comment by rozukke** [comment]
Fixed in #106
