### ISSUE TITLE
Missing command in `getPlayerTilePosition()`

### ISSUE THREAD

**Issue by nhatdongdang** [rozukke/mcpp#28]
### Description:
The `getPlayerTilePosition()` function in the `MinecraftConnection` class contains a potential issue where the command `player.` is incomplete. This could lead to unexpected behavior or errors when attempting to retrieve the player's position.

**Code Snippet:**
```cpp
Coordinate MinecraftConnection::getPlayerTilePosition() {
    std::string returnString = conn->sendReceiveCommand("player.", "");
    std::vector<int> parsedInts;
    splitCommaStringToInts(returnString, parsedInts);
    return Coordinate(parsedInts[0], parsedInts[1], parsedInts[2]);
}

**Comment by johnathanchann** [comment]
Apologize for the mistakes caused, will be more wary in the future.
